test:
  ribbon:
    listOfServers: www.baidu.com:80,www.163.com:80
    ReadTimeout: 10000
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

test2:
  ribbon:
    listOfServers: www.baidu.com:80,www.163.com:80
    ReadTimeout: 10000
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

ribbon:
  eureka:
   enabled: false

ribbon:
  eager-load:
    enabled: true
    clients: test,test2